---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_distribution_release != 'xenial'

- include_vars: "Ubuntu1604.yml"
  when: ansible_distribution_release == 'xenial'

# Install RedHat-like
- include: squid3-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Install Debian-like
- include: squid3-Debian.yml
  when: ansible_os_family == 'Debian' and not ansible_distribution_release == 'xenial'

# Install Ubuntu 16.04
- include: squid3-Ubuntu1604.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
