---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_distribution_release != 'xenial'

- include_vars: "Ubuntu1604.yml"
  when: ansible_distribution_release == 'xenial'

# Install RedHat-like
- include: squid3-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Install Debian-like
- include: squid3-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy logrotate config for squid3
  template:
    src: etc/logrotate.d/squid.j2
    dest: /etc/logrotate.d/squid
    owner: root
    group: root
    mode: 0644

- name: Add squid to autoboot
  service:
    name: "{{ squid3__daemon }}"
    state: started
    enabled: yes
